locals {
  website_bucket_name = var.project_name
}

#----OIDC Provider------------------------------------
resource "aws_iam_openid_connect_provider" "github" {
  url             = "https://token.actions.githubusercontent.com"
  client_id_list  = ["sts.amazonaws.com"]
  thumbprint_list = ["6938fd4d98bab03faadb97b34396831e3780aea1"]
}

#-----Shared Trust Policy-------------------------------
# Both roles use the same trust policy - only repo on main can assume them
data "aws_iam_policy_document" "github_assume_role" {
  statement {
    actions = ["sts:AssumeRoleWithWebIdentity"]
    effect  = "Allow"

    principals {
      type        = "Federated"
      identifiers = [aws_iam_openid_connect_provider.github.arn]
    }

    condition {
      test     = "StringEquals"
      variable = "token.actions.githubusercontent.com:aud"
      values   = ["sts.amazonaws.com"]
    }

    condition {
      test     = "StringEquals"
      variable = "token.actions.githubusercontent.com:sub"
      values   = ["repo:${var.github_org}/${var.github_repo}:ref:refs/heads/main"]
    }
  }
}

#----ROLE 1: Terraform---------------------------------------------
# Broad permissions scoped to managing this project's infrastructure only
# S3 and CloudFront are scoped by naming convention here and tightened
# to specific ARNs by infra/ after the first apply

data "aws_caller_identity" "current" {}

data "aws_iam_policy_document" "terraform_permissions" {

  # Full access to state bucket
  statement {
    effect    = "Allow"
    actions   = ["s3:*"]
    resources = [
      "arn:aws:s3:::${var.tfstate_bucket}",
      "arn:aws:s3:::${var.tfstate_bucket}/*"
    ]
  }

  # Full access to site bucket
  statement {
    effect    = "Allow"
    actions   = ["s3:*"]
    resources = [
      "arn:aws:s3:::${local.website_bucket_name}",
      "arn:aws:s3:::${local.website_bucket_name}/*"
    ]
  }

  # CloudFront
  statement {
    effect    = "Allow"
    actions   = ["cloudfront:*"]
    resources = ["arn:aws:cloudfront::${data.aws_caller_identity.current.account_id}:distribution/*"]
  }

  # IAM, API Gateway, CloudWatch Logs
  statement {
    effect    = "Allow"
    actions   = ["apigateway:*", "logs:*", "iam:*"]
    resources = ["*"]
  }

  

  # Site S3 bucket - scoped to project naming convention
  # IMPORTANT: your site bucket name in infra/ must be var.project_name
  # This is tightened to the specific ARN by infra/ after first apply
  statement {
    effect  = "Allow"
    actions = ["s3:*"]
    resources = [
      "arn:aws:s3:::${local.website_bucket_name}*",
      "arn:aws:s3:::${local.website_bucket_name}/*"
    ]
  }

  # CloudFront - scoped to account
  # Tightened to specific distribution ARN by infra/ after first apply
  statement {
    effect    = "Allow"
    actions   = ["cloudfront:CreateInvalidation"]
    resources = ["arn:aws:cloudfront::${data.aws_caller_identity.current.account_id}:distribution/*"]
  }

  # IAM, API Gateway, CloudWatch Logs - must remain broad
  # API Gateway: resource IDs generated by AWS, not predictable
  # Logs: log group ARNs created at Lambda runtime, not at apply
  statement {
    effect    = "Allow"
    actions   = ["apigateway:*", "logs:*"]
    resources = ["*"]
  }

  # IAM - scoped to roles and policies only, no users or groups
  # Further scoped to project naming convention
  statement {
    effect  = "Allow"
    actions = ["iam:*"]
    resources = [
      "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/${var.project_name}-*",
      "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/github-actions-*",
      "arn:aws:iam::${data.aws_caller_identity.current.account_id}:policy/${var.project_name}-*",
      "arn:aws:iam::${data.aws_caller_identity.current.account_id}:oidc-provider/*"
    ]
  }
}

resource "aws_iam_role" "terraform" {
  name               = "github-actions-terraform"
  assume_role_policy = data.aws_iam_policy_document.github_assume_role.json
  tags               = merge(var.tags, { Name = "github-actions-terraform" })
}

resource "aws_iam_role_policy" "terraform_permissions" {
  name   = "terraform-permissions"
  role   = aws_iam_role.terraform.id
  policy = data.aws_iam_policy_document.terraform_permissions.json
}

#-----ROLE 2: Deploy------------------------------------
# Minimal permissions - only what the pipeline needs to upload files
# to the static site bucket and invalidate the CloudFront cache
data "aws_iam_policy_document" "github_deploy_permissions" {

  statement {
    effect    = "Allow"
    actions   = ["s3:ListBucket"]
    resources = ["arn:aws:s3:::${local.website_bucket_name}"]
  }

  statement {
    effect = "Allow"
    actions = [
      "s3:PutObject",
      "s3:DeleteObject"
    ]
    resources = ["arn:aws:s3:::${local.website_bucket_name}/*"]
  }

  statement {
    effect    = "Allow"
    actions   = ["cloudfront:CreateInvalidation"]
    resources = ["arn:aws:cloudfront::${data.aws_caller_identity.current.account_id}:distribution/*"]
  }
}

resource "aws_iam_role" "github_deploy" {
  name               = "github-actions-deploy"
  assume_role_policy = data.aws_iam_policy_document.github_assume_role.json
  tags               = merge(var.tags, { Name = "github-actions-deploy-role" })
}

resource "aws_iam_role_policy" "github_deploy_permissions" {
  name   = "github-deploy-permissions"
  role   = aws_iam_role.github_deploy.id
  policy = data.aws_iam_policy_document.github_deploy_permissions.json
}
