#----OIDC Provider------------------------------------
resource "aws_iam_openid_connect_provider" "github" {
  url             = "https://token.actions.githubusercontent.com"
  client_id_list  = ["sts.amazonaws.com"]
  thumbprint_list = ["6938fd4d98bab03faadb97b34396831e3780aea1"]
}
#Two roles - One with broad permissions to deploy terraform, and another
#with minimal permissions so pipeline can update site and invalidate cloudfront cache

#-----Shared Trusted policy-------------------------------
#Both roles use the same trust policy - only repo on main can assume them
data "aws_iam_policy_document" "github_assume_role" {
  statement {
    actions = ["sts:AssumeRoleWithWebIdentity"]
    effect  = "Allow"

    principals {
      type        = "Federated"
      identifiers = [aws_iam_openid_connect_provider.github.arn]
    }

    condition {
      test     = "StringEquals"
      variable = "token.actions.githubusercontent.com:aud"
      values   = ["sts.amazonaws.com"]
    }

    condition {
      test     = "StringEquals"
      variable = "token.actions.githubusercontent.com:sub"
      values   = ["repo:${var.github_org}/${var.github_repo}:ref:refs/heads/main"]
    }
  }
}
#----ROLE 1 Terraform---------------------------------------------
# Broad permissions scoped to managing this project's infrastructure only

data "aws_caller_identity" "current" {}

data "aws_iam_policy_document" "terraform_permissions" {

  # State bucket- fully scoped
  statement {
    effect = "Allow"
    actions = [
      "s3:GetObject",
      "s3:PutObject",
      "s3:DeleteObject"
    ]
    resources = [
      "arn:aws:s3:::${var.tfstate_bucket}/${var.tf_state_bucket_key}/terraform.tfstate",
    ]
  }

  statement {
    effect    = "Allow"
    actions   = ["s3:ListBucket"]
    resources = ["arn:aws:s3:::${var.tfstate_bucket}"]
  }

  #DynamoDB lock - fully scoped
  statement {
    effect = "Allow"
    actions = [
      "dynamodb:GetItem",
      "dynamodb:PutItem",
      "dynamodb:DeleteItem"
    ]

    resources = ["arn:aws:dynamodb:${var.dynamodb_lock_table_region}:${data.aws_caller_identity.current.account_id}:table/${var.dynamodb_lock_table}"]
  }

  #Site S3 bucket - scoped to specific bucket
  statement {
    effect = "Allow"
    actions = [
      "s3:*"
    ]
    resources = [var.static_website_bucket_arn,
    "${var.static_website_bucket_arn}/*"]
  }

  #Invalidates CloudFront cache - scoped to specific distribution
  statement {
    effect    = "Allow"
    actions   = ["cloudfront:CreateInvalidation"]
    resources = [var.cloudfront_distribution_arn]
  }

  # IAM, API Gateway, CloudWatch logs - must remain broad
  # API Gateway: resource IDs generated by AWS, not predicatable
  # Logs: log group ARNs creaed at Lambda runtime, not at apply
  statement {
    effect    = "Allow"
    actions   = ["apigateway:*", "logs:*"]
    resources = ["*"]
  }

  # IAM - scoped to roles and policies only, no users or groups
  # Further scoped to project naming convention
  statement {
    effect  = "Allow"
    actions = ["iam:*"]
    resources = [
      "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/portfolio-*",
      "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/github-actions-*",
      "arn:aws:iam::${data.aws_caller_identity.current.account_id}:policy/portfolio-*",
      "arn:aws:iam::${data.aws_caller_identity.current.account_id}:oidc-provider/*"


    ]
  }
}

resource "aws_iam_role" "terraform" {
  name               = "github-actions-terraform"
  assume_role_policy = data.aws_iam_policy_document.github_assume_role.json
  tags               = merge(var.tags, { Name = "github-actions-terraform" })
}

resource "aws_iam_role_policy" "terraform_permissions" {
  name   = "terraform-permissions"
  role   = aws_iam_role.terraform.id
  policy = data.aws_iam_policy_document.terraform_permissions.json
}

#-----ROLE 2: Deploy------------------------------------
#Minimal permissions - only what the pipeline needs to upload files to static site bucket and invalidate cloudfront cache
data "aws_iam_policy_document" "github_deploy_permissions" {

  statement {
    effect    = "Allow"
    actions   = ["s3:ListBucket"]
    resources = [var.static_website_bucket_arn]
  }

  statement {
    effect = "Allow"
    actions = [
      "s3:PutObject",
      "s3:DeleteObject"
    ]
    resources = ["${var.static_website_bucket_arn}/*"]
  }

  statement {
    effect    = "Allow"
    actions   = ["cloudfront:CreateInvalidation"]
    resources = [var.cloudfront_distribution_arn]
  }
}

resource "aws_iam_role" "github_deploy" {
  name               = "github-actions-deploy"
  assume_role_policy = data.aws_iam_policy_document.github_assume_role.json
  tags               = merge(var.tags, { Name = "github-actions-deploy-role" })
}

resource "aws_iam_role_policy" "github_deploy-permissions" {
  name   = "github-deploy-permissions"
  role   = aws_iam_role.github_deploy.id
  policy = data.aws_iam_policy_document.github_deploy_permissions.json
}